### ISSUE TITLE
`requestActivityTransitionUpdates` throws `SecurityException` after some time and stops getting activities

### ISSUE THREAD

**Issue by raphael-dario** [googlecodelabs/activity_transitionapi-codelab#27]
Hi.
This happens after 2~3 days of using my app to track walking and running. Here is the code which is called every hour in the `onStartJob` of a JobService.
```kotlin
val request = ActivityTransitionWalkRequest.build()
val client = ActivityRecognition.getClient(appContext)
client
                .requestActivityTransitionUpdates(request, getPendingIntent(context))
                .apply {
                    addOnSuccessListener { onDone.invoke(true) }
                    addOnFailureListener { onDone.invoke(false) }
                }
```

I see from my logs that `addOnSuccessListener` is called, but also that the a `SecurityException` is thrown, and my BroadcastReceiver doesn't receive any transition events anymore. Here is some stacktrace:
```
16:51:27.602  E  Bad call made by uid 10116. Package "xxx.xxx" does not belong to uid 10283.
16:51:27.602  E  checkOperation
                 java.lang.SecurityException: Specified package "xxx.xxx" under uid 10283 but it is not
                 	at com.android.server.appop.AppOpsService.verifyAndGetBypass(AppOpsService.java:4696)
                 	at com.android.server.appop.AppOpsService.verifyAndGetBypass(AppOpsService.java:4564)
                 	at com.android.server.appop.AppOpsService.checkOperationUnchecked(AppOpsService.java:3253)
                 	at com.android.server.appop.AppOpsService.checkOperationImpl(AppOpsService.java:3236)
                 	at com.android.server.appop.AppOpsService.-$$Nest$mcheckOperationImpl(Unknown Source:0)
                 	at com.android.server.appop.AppOpsService$CheckOpsDelegateDispatcher.lambda$checkOperation$0(AppOpsService.java:7596)
                 	at com.android.server.appop.AppOpsService$CheckOpsDelegateDispatcher.$r8$lambda$KrwrxMLmGzFSEjEyo0aJ63o5J9E(Unknown Source:0)
                 	at com.android.server.appop.AppOpsService$CheckOpsDelegateDispatcher$$ExternalSyntheticLambda9.apply(Unknown Source:24)
                 	at com.android.server.policy.AppOpsPolicy.checkOperation(AppOpsPolicy.java:213)
                 	at com.android.server.appop.AppOpsService$CheckOpsDelegateDispatcher.checkOperation(AppOpsService.java:7595)
                 	at com.android.server.appop.AppOpsService.checkOperation(AppOpsService.java:3223)
                 	at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:457)
                 	at android.os.Binder.execTransactInternal(Binder.java:1280)
                 	at android.os.Binder.execTransact(Binder.java:1244)
```

What can be the cause of this?
Thanks for any help. I can provide more source if needed.

**Extra Note**
in the `addOnSuccessListener` callback, I register a broadcast receiver like this:
```kotlin
unregisterReceiver(transitionsReceiver)

if (transitionsReceiver == null) {
    transitionsReceiver = ActivityTransitionReceiver()
}
registerReceiver(transitionsReceiver, IntentFilter(RECEIVER_ACTION))
```

Another observation: after restarting the phone, the security exception is no longer thrown and I receive transition updates.

**Device / OS**
Pixel 6 / Android 13

**Comment by raphael-dario** [comment]
**SOLUTION**: What I have noticed is that in this case we are calling `requestActivityTransitionUpdates` multiple times without removing the previous request with the same pending intent. so my solution (which seems to work fine for more than 2 weeks) is to `removeActivityTransitionUpdates` for the pending intent before calling `requestActivityTransitionUpdates`. something similar to this:

```kotlin
client.removeActivityTransitionUpdates(getPendingIntent(context))
    .addOnCompleteListener {
        client
            .requestActivityTransitionUpdates(request, getPendingIntent(context))
            .apply {
                addOnSuccessListener { onDone.invoke(true) }
                addOnFailureListener { onDone.invoke(false) }
            }
    }
```
